name: Qodana
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
  pull_request:
    types:
      - ready_for_review
    branches:
      - master
      - develop

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2022.1.1
