name: Java CI with Maven
'on':
  push:
    branches:
      - master
      - develop
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - unlocked
    branches:
      - master
      - develop

jobs:
  build:
    strategy:
      matrix:
        version: [ 8, 11, 16 ]
        os: [ "ubuntu-latest" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java ${{ matrix.version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.version }}
          distribution: adopt
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Create necessary directories
        run: mkdir staging && cp target/*.jar staging
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: '${{ github.event.repository.name }}-${{ github.sha }}'
          path: staging
