name: Publish package to the Package Repository
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up the Package Repository
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'adopt'
          server-id: cloudsmith
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.CLOUDSMITH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.CLOUDSMITH_TOKEN }}